version: 2.1

parameters:

  main_workflow:
    type: boolean
    default: true

  # A parameter per package
  backend:
    type: boolean
    default: false
  frontend:
    type: boolean
    default: false

executors:
  alpine:
    docker:
      - image: circleci/node

jobs:
  check-folder:
    executor: alpine
    steps:
      - checkout
      - run:
          name: Trigger workflows
          command: chmod +x ./circle_trigger.sh && ./circle_trigger.sh

  build:
    parameters:
      package_name:
        type: string

    executor: alpine
    working_directory: ~/project/packages/<< parameters.package_name >>

    steps:
      - checkout:
          path: ~/project
      # This step is added only to show that we are in the package directory
      - run:
          name: Content 
          command: |
            cat README.md 
            echo "<< parameters.package_name >> built." > build.txt

workflows:
  version: 2

  # The main workflow responsible for triggering all other workflows
  # in which changes are detected.
  ci:
    when: << pipeline.parameters.main_workflow >>
    jobs:
      - check-folder


  # Workflows defined for each package.

  backend:
    when: << pipeline.parameters.backend >>
    jobs:
      - build:
          name: backend-build
          package_name: backend
  
  frontend:
    when: << pipeline.parameters.frontend >>
    jobs:
      - build:
          name: frontend-build
          package_name: frontend
      