version: 2.1
jobs:
  build:
    docker:
      - image: alpine:3.7

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: date

workflow:
  version: 2
  main_workflow:
    jobs:
      - build:
        filters:
          branches:
            only: "ci-setup"