---
version: 2.1

jobs:

  build_frontend:
    working_directory: ~/project/packages/frontend/app
    docker:
      - image: circleci/node
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Run Yarn
          command: yarn
      - run:
          name: Run Yarn CI Tests
          command: yarn test:ci
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: |
            cd .. && docker build -t codurance/open-space:${CIRCLE_SHA1} .
            docker tag codurance/open-space:${CIRCLE_SHA1} codurance/open-space:latest
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
              echo "$DOCKER_HUB_PASS" | docker login -u "$DOCKER_HUB_USER_NAME" --password-stdin
              docker push codurance/open-space:${CIRCLE_SHA1}
              docker push codurance/open-space:latest

  build_backend:
    working_directory: ~/project/packages/backend
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Build and Run Test
          command: ./gradlew test
      - run:
          name: Generate Dockerfile
          command: ./gradlew dockerCreateDockerfile
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: |
              cd build/docker && docker build -t codurance/open-space-backend:${CIRCLE_SHA1} .
              docker tag codurance/open-space-backend:${CIRCLE_SHA1} codurance/open-space-backend:latest
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
              echo "$DOCKER_HUB_PASS" | docker login -u "$DOCKER_HUB_USER_NAME" --password-stdin
              docker push codurance/open-space-backend:${CIRCLE_SHA1}
              docker push codurance/open-space-backend:latest

  deploy:
    docker:
      - image: hashicorp/terraform
    working_directory: ~/project/terraform
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Initialize Terraform
          command: terraform init
      - run:
          name: Deploy
          command: env TF_VAR_app_image=codurance/open-space:${CIRCLE_SHA1} TF_VAR_app_backend_image=codurance/open-space-backend:${CIRCLE_SHA1} terraform apply -auto-approve

workflows:
  version: 2

  build:
    jobs:
      - build_frontend
      - build_backend
      - deploy:
          requires:
            - build_frontend
            - build_backend
