version: 2.1

jobs:

  build_frontend:

    working_directory: ~/project/packages/frontend/app

    docker:
      - image: circleci/node

    steps:
      - checkout: 
          path: ~/project
      - run:
          name: Run Yarn
          command: yarn
      - run:
          name: Run Yarn CI Tests
          command: yarn test:ci
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: cd .. && docker build -t codurance/open-space:${CIRCLE_SHA1} .
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
              echo "$DOCKER_HUB_PASS" | docker login -u "$DOCKER_HUB_USER_NAME" --password-stdin
              docker push codurance/open-space:${CIRCLE_SHA1}

workflows:
  version: 2

  build:
    jobs:
      - build_frontend
      