spring:
  profiles:
    active: dev

---

spring:
  profiles: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://postgres:5432/open-space"
    username: postgres
    password: example
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

---

spring:
  profiles: prod
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://open-space.czxuatmdut7q.eu-west-2.rds.amazonaws.com:5432/"
    username: postgres
    password: ${PROD_DB_PASSWD}
    initialization-mode: never
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
