spring:
  profiles:
    active: dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    properties:
      hibernate:
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
---

spring:
  profiles: dev-container
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://postgres:5432/open-space"
    username: postgres
    password: example
    initialization-mode: always

---

spring:
  profiles: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/open-space"
    username: postgres
    password: example
    initialization-mode: always

---

spring:
  profiles: prod
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://open-space.czxuatmdut7q.eu-west-2.rds.amazonaws.com:5432/"
    username: postgres
    password: ${PROD_DB_PASSWD}
    initialization-mode: never
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
