version: '3'
services:
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: open-space
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  spring:
    build: build/docker/.
    ports:
      - "8080:8080"
    links:
      - postgres
volumes:
  db-data:
    driver: local